// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: media.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaUpload_UploadVideo_FullMethodName = "/media.MediaUpload/UploadVideo"
)

// MediaUploadClient is the client API for MediaUpload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaUploadClient interface {
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadStatus], error)
}

type mediaUploadClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaUploadClient(cc grpc.ClientConnInterface) MediaUploadClient {
	return &mediaUploadClient{cc}
}

func (c *mediaUploadClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaUpload_ServiceDesc.Streams[0], MediaUpload_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VideoChunk, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaUpload_UploadVideoClient = grpc.ClientStreamingClient[VideoChunk, UploadStatus]

// MediaUploadServer is the server API for MediaUpload service.
// All implementations must embed UnimplementedMediaUploadServer
// for forward compatibility.
type MediaUploadServer interface {
	UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadStatus]) error
	mustEmbedUnimplementedMediaUploadServer()
}

// UnimplementedMediaUploadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaUploadServer struct{}

func (UnimplementedMediaUploadServer) UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadStatus]) error {
	return status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedMediaUploadServer) mustEmbedUnimplementedMediaUploadServer() {}
func (UnimplementedMediaUploadServer) testEmbeddedByValue()                     {}

// UnsafeMediaUploadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaUploadServer will
// result in compilation errors.
type UnsafeMediaUploadServer interface {
	mustEmbedUnimplementedMediaUploadServer()
}

func RegisterMediaUploadServer(s grpc.ServiceRegistrar, srv MediaUploadServer) {
	// If the following call pancis, it indicates UnimplementedMediaUploadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaUpload_ServiceDesc, srv)
}

func _MediaUpload_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaUploadServer).UploadVideo(&grpc.GenericServerStream[VideoChunk, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaUpload_UploadVideoServer = grpc.ClientStreamingServer[VideoChunk, UploadStatus]

// MediaUpload_ServiceDesc is the grpc.ServiceDesc for MediaUpload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaUpload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaUpload",
	HandlerType: (*MediaUploadServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadVideo",
			Handler:       _MediaUpload_UploadVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "media.proto",
}
