FROM golang:1.25.1 AS builder

WORKDIR /app

# Copy go.mod and go.sum first 
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the image 
COPY ./producer ./
COPY ./proto ./proto
COPY ./videos ./videos

# Build server.go
RUN go build -o producer

FROM gcr.io/distroless/base

WORKDIR /app

# Copy the built producer binary
COPY --from=builder /app/producer .

EXPOSE 50051

CMD ["./producer"]
