FROM golang:1.25.1 AS builder

WORKDIR /app

# Copy go.mod and go.sum first 
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY ./consumer ./
COPY ./proto ./proto

# Build client.go
RUN go build -o consumer

FROM gcr.io/distroless/base

WORKDIR /app
COPY --from=builder /app/consumer .
COPY --from=builder /app/web ./web

EXPOSE 50051 8080

CMD ["./consumer"]
